---
- name: Converge
  hosts:
    - test-multi-01
    - test-multi-02
    - test-multi-03
  tasks:
    - name: install iproute
      dnf:
        name: iproute

- name: Converge
  hosts:
    - test-multi-01
    - test-multi-02
    - test-multi-03
  any_errors_fatal: true
  roles:
    - ../redis
